INSERT INTO eproperty_propertyimages (propertyImageID, propertyImage, propertyImageDescription, propertyID_id) VALUES (1, 'images_1.jpg', 'Facing', 1);
INSERT INTO eproperty_propertyimages (propertyImageID, propertyImage, propertyImageDescription, propertyID_id) VALUES (2, 'images.jpg', 'Front Facing', 1);
INSERT INTO eproperty_propertyimages (propertyImageID, propertyImage, propertyImageDescription, propertyID_id) VALUES (6, '185846_2.jpg', 'Condo', 4);
INSERT INTO eproperty_propertyimages (propertyImageID, propertyImage, propertyImageDescription, propertyID_id) VALUES (7, 'Bangkok-townhouse-baan-puripuri-1.jpg', 'Townhouse', 2);
INSERT INTO eproperty_propertyimages (propertyImageID, propertyImage, propertyImageDescription, propertyID_id) VALUES (8, 'CN_Tower.jpg', 'Cn Tower at Day', 3);
INSERT INTO eproperty_propertyimages (propertyImageID, propertyImage, propertyImageDescription, propertyID_id) VALUES (9, 'tower.jpg', 'Tower at night', 3);
INSERT INTO eproperty_propertyimages (propertyImageID, propertyImage, propertyImageDescription, propertyID_id) VALUES (10, 'swimming-pool-house-shed-ny.jpg', 'Swimming pool', 1);
INSERT INTO eproperty_propertyimages (propertyImageID, propertyImage, propertyImageDescription, propertyID_id) VALUES (11, 'mayfair.png', 'Front overview of the house', 5);
INSERT INTO eproperty_propertyimages (propertyImageID, propertyImage, propertyImageDescription, propertyID_id) VALUES (12, '139013_1.jpg', 'Backyard of house', 5);
INSERT INTO eproperty_propertyimages (propertyImageID, propertyImage, propertyImageDescription, propertyID_id) VALUES (13, 'images_8bZhJNZ.jpg', 'close view of property', 6);
INSERT INTO eproperty_propertyimages (propertyImageID, propertyImage, propertyImageDescription, propertyID_id) VALUES (14, '4765708.jpg', 'Rear view of the property', 6);
INSERT INTO eproperty_propertyimages (propertyImageID, propertyImage, propertyImageDescription, propertyID_id) VALUES (15, 'images_1_riKOmyw.jpg', 'Backyard of house', 6);