INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (1, 1, 'add_logentry', 'Can add log entry');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (2, 1, 'change_logentry', 'Can change log entry');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (3, 1, 'delete_logentry', 'Can delete log entry');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (4, 1, 'view_logentry', 'Can view log entry');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (5, 2, 'add_permission', 'Can add permission');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (6, 2, 'change_permission', 'Can change permission');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (7, 2, 'delete_permission', 'Can delete permission');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (8, 2, 'view_permission', 'Can view permission');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (9, 3, 'add_group', 'Can add group');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (10, 3, 'change_group', 'Can change group');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (11, 3, 'delete_group', 'Can delete group');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (12, 3, 'view_group', 'Can view group');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (13, 4, 'add_user', 'Can add user');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (14, 4, 'change_user', 'Can change user');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (15, 4, 'delete_user', 'Can delete user');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (16, 4, 'view_user', 'Can view user');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (17, 5, 'add_contenttype', 'Can add content type');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (18, 5, 'change_contenttype', 'Can change content type');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (19, 5, 'delete_contenttype', 'Can delete content type');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (20, 5, 'view_contenttype', 'Can view content type');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (21, 6, 'add_session', 'Can add session');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (22, 6, 'change_session', 'Can change session');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (23, 6, 'delete_session', 'Can delete session');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (24, 6, 'view_session', 'Can view session');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (25, 7, 'add_city', 'Can add city');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (26, 7, 'change_city', 'Can change city');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (27, 7, 'delete_city', 'Can delete city');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (28, 7, 'view_city', 'Can view city');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (29, 8, 'add_country', 'Can add country');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (30, 8, 'change_country', 'Can change country');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (31, 8, 'delete_country', 'Can delete country');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (32, 8, 'view_country', 'Can view country');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (33, 9, 'add_password', 'Can add password');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (34, 9, 'change_password', 'Can change password');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (35, 9, 'delete_password', 'Can delete password');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (36, 9, 'view_password', 'Can view password');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (37, 10, 'add_permissiontyoe', 'Can add permission tyoe');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (38, 10, 'change_permissiontyoe', 'Can change permission tyoe');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (39, 10, 'delete_permissiontyoe', 'Can delete permission tyoe');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (40, 10, 'view_permissiontyoe', 'Can view permission tyoe');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (41, 11, 'add_property', 'Can add property');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (42, 11, 'change_property', 'Can change property');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (43, 11, 'delete_property', 'Can delete property');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (44, 11, 'view_property', 'Can view property');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (45, 12, 'add_property_facing', 'Can add property_ facing');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (46, 12, 'change_property_facing', 'Can change property_ facing');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (47, 12, 'delete_property_facing', 'Can delete property_ facing');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (48, 12, 'view_property_facing', 'Can view property_ facing');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (49, 13, 'add_property_sector', 'Can add property_ sector');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (50, 13, 'change_property_sector', 'Can change property_ sector');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (51, 13, 'delete_property_sector', 'Can delete property_ sector');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (52, 13, 'view_property_sector', 'Can view property_ sector');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (53, 14, 'add_propertycategory', 'Can add property category');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (54, 14, 'change_propertycategory', 'Can change property category');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (55, 14, 'delete_propertycategory', 'Can delete property category');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (56, 14, 'view_propertycategory', 'Can view property category');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (57, 15, 'add_propertyimages', 'Can add property images');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (58, 15, 'change_propertyimages', 'Can change property images');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (59, 15, 'delete_propertyimages', 'Can delete property images');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (60, 15, 'view_propertyimages', 'Can view property images');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (61, 16, 'add_province', 'Can add province');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (62, 16, 'change_province', 'Can change province');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (63, 16, 'delete_province', 'Can delete province');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (64, 16, 'view_province', 'Can view province');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (65, 17, 'add_rolecode', 'Can add role code');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (66, 17, 'change_rolecode', 'Can change role code');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (67, 17, 'delete_rolecode', 'Can delete role code');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (68, 17, 'view_rolecode', 'Can view role code');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (69, 18, 'add_rolepermission', 'Can add role permission');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (70, 18, 'change_rolepermission', 'Can change role permission');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (71, 18, 'delete_rolepermission', 'Can delete role permission');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (72, 18, 'view_rolepermission', 'Can view role permission');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (73, 19, 'add_userrole', 'Can add user role');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (74, 19, 'change_userrole', 'Can change user role');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (75, 19, 'delete_userrole', 'Can delete user role');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (76, 19, 'view_userrole', 'Can view user role');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (77, 20, 'add_users', 'Can add users');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (78, 20, 'change_users', 'Can change users');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (79, 20, 'delete_users', 'Can delete users');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (80, 20, 'view_users', 'Can view users');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (81, 21, 'add_rolepermissiondetail', 'Can add role permission detail');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (82, 21, 'change_rolepermissiondetail', 'Can change role permission detail');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (83, 21, 'delete_rolepermissiondetail', 'Can delete role permission detail');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (84, 21, 'view_rolepermissiondetail', 'Can view role permission detail');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (85, 10, 'add_permissiontype', 'Can add permission type');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (86, 10, 'change_permissiontype', 'Can change permission type');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (87, 10, 'delete_permissiontype', 'Can delete permission type');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (88, 10, 'view_permissiontype', 'Can view permission type');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (89, 22, 'add_users', 'Can add users');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (90, 22, 'change_users', 'Can change users');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (91, 22, 'delete_users', 'Can delete users');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (92, 22, 'view_users', 'Can view users');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (93, 23, 'add_rolepermissiondetail', 'Can add role permission detail');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (94, 23, 'change_rolepermissiondetail', 'Can change role permission detail');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (95, 23, 'delete_rolepermissiondetail', 'Can delete role permission detail');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (96, 23, 'view_rolepermissiondetail', 'Can view role permission detail');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (97, 24, 'add_propertycategory', 'Can add property category');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (98, 24, 'change_propertycategory', 'Can change property category');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (99, 24, 'delete_propertycategory', 'Can delete property category');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (100, 24, 'view_propertycategory', 'Can view property category');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (101, 25, 'add_city', 'Can add city');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (102, 25, 'change_city', 'Can change city');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (103, 25, 'delete_city', 'Can delete city');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (104, 25, 'view_city', 'Can view city');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (105, 26, 'add_password', 'Can add password');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (106, 26, 'change_password', 'Can change password');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (107, 26, 'delete_password', 'Can delete password');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (108, 26, 'view_password', 'Can view password');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (109, 27, 'add_userrole', 'Can add user role');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (110, 27, 'change_userrole', 'Can change user role');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (111, 27, 'delete_userrole', 'Can delete user role');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (112, 27, 'view_userrole', 'Can view user role');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (113, 28, 'add_advertisement', 'Can add advertisement');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (114, 28, 'change_advertisement', 'Can change advertisement');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (115, 28, 'delete_advertisement', 'Can delete advertisement');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (116, 28, 'view_advertisement', 'Can view advertisement');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (117, 29, 'add_rolecode', 'Can add role code');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (118, 29, 'change_rolecode', 'Can change role code');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (119, 29, 'delete_rolecode', 'Can delete role code');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (120, 29, 'view_rolecode', 'Can view role code');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (121, 30, 'add_province', 'Can add province');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (122, 30, 'change_province', 'Can change province');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (123, 30, 'delete_province', 'Can delete province');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (124, 30, 'view_province', 'Can view province');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (125, 31, 'add_rolepermission', 'Can add role permission');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (126, 31, 'change_rolepermission', 'Can change role permission');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (127, 31, 'delete_rolepermission', 'Can delete role permission');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (128, 31, 'view_rolepermission', 'Can view role permission');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (129, 32, 'add_country', 'Can add country');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (130, 32, 'change_country', 'Can change country');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (131, 32, 'delete_country', 'Can delete country');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (132, 32, 'view_country', 'Can view country');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (133, 33, 'add_property_facing', 'Can add property_ facing');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (134, 33, 'change_property_facing', 'Can change property_ facing');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (135, 33, 'delete_property_facing', 'Can delete property_ facing');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (136, 33, 'view_property_facing', 'Can view property_ facing');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (137, 34, 'add_permissiontype', 'Can add permission type');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (138, 34, 'change_permissiontype', 'Can change permission type');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (139, 34, 'delete_permissiontype', 'Can delete permission type');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (140, 34, 'view_permissiontype', 'Can view permission type');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (141, 35, 'add_property', 'Can add property');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (142, 35, 'change_property', 'Can change property');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (143, 35, 'delete_property', 'Can delete property');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (144, 35, 'view_property', 'Can view property');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (145, 36, 'add_property_sector', 'Can add property_ sector');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (146, 36, 'change_property_sector', 'Can change property_ sector');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (147, 36, 'delete_property_sector', 'Can delete property_ sector');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (148, 36, 'view_property_sector', 'Can view property_ sector');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (149, 37, 'add_propertyimages', 'Can add property images');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (150, 37, 'change_propertyimages', 'Can change property images');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (151, 37, 'delete_propertyimages', 'Can delete property images');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (152, 37, 'view_propertyimages', 'Can view property images');