# Generated by Django 2.1.3 on 2018-12-08 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eproperty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='propertyID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='eproperty.Property'),
        ),
    ]
