# Generated by Django 2.1.3 on 2018-12-09 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eproperty', '0004_auto_20181208_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='user_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eproperty.Users'),
            preserve_default=False,
        ),
    ]
