# Generated by Django 2.1.3 on 2018-12-09 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eproperty', '0006_propertyimages_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimages',
            name='user_ID',
        ),
    ]
